api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("data.urls"))
]

data/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('sug/', views.sug),
    path('rank/', views.rank)


]

data/models.py
from django.db import models
from django.forms import ModelForm


class Review(models.Model):
    name = models.CharField(max_length=50)
    mob = models.BigIntegerField()
    msg = models.CharField(max_length=1000)

    def __str__(self):
        return self.name


class Search(models.Model):
    country_name = models.CharField(max_length=40)


class Searchform(ModelForm):
    class Meta:
        model = Search
        fields = ['country_name']


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['name', 'mob', 'msg']

data/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ReviewForm, Review, Search, Searchform
import requests
import json


def index(request):
    selected_tret = 0

    all_con = 0
    all_rec = 0
    all_dead = 0
    top_t_con = 0
    top_t_tret = 0
    death_rate = 0
    top_t_dead = 0
    top_t_rec = 0
    data_json = requests.get("https://api.covid19api.com/summary")
    list_all = []
    top_t = []
    data = data_json.text
    data_d = json.loads(data)
    list_l = data_d['Countries']
    for e in range(len(list_l)):
        if list_l[e]['Country'] == 'India':

            selected_con = int(list_l[e]['TotalConfirmed'])
            selected_dead = int(list_l[e]['TotalDeaths'])
            selected_rec = int(list_l[e]['TotalRecovered'])
            selected_tret = selected_con - selected_dead - selected_rec
            if selected_con == 0:
                sel_death_rate = 0
            else:
                sel_death_rate = round(selected_dead * 100 / selected_con, 2)
            selected_name = list_l[e]['Country']

    for j in list_l:
        list_all.append(int(j['TotalConfirmed']))
        all_con += int(j['TotalConfirmed'])
        all_dead += int(j['TotalDeaths'])
        all_rec += int(j['TotalRecovered'])
        if all_con == 0:
            death_rate = 0
        else:
            death_rate = round((all_dead / all_con) * 100, 2)

    list_all.sort()
    list_all.reverse()
    k = list_all[0:10]
    for r in range(len(k)):
        for s in list_l:

            if k[r] == s['TotalConfirmed']:
                top_t.append(s)
                top_t_con += s['TotalConfirmed']

    for o in top_t:
        top_t_dead += int(o['TotalDeaths'])
        top_t_rec += int(o['TotalRecovered'])
    top_t_tret = top_t_dead + top_t_rec

    if request.method == "POST":
        error = ""
        a = False
        form = Searchform(request.POST)
        country_name = form.data['country_name']
        for h in list_l:
            if country_name == str(h['Country']) or country_name == h['Country'].upper() or country_name == h[
                'Country'].lower():
                selected_name = h['Country']
                selected_con = int(h['TotalConfirmed'])
                selected_dead = int(h['TotalDeaths'])
                selected_rec = int(h['TotalRecovered'])
                selected_tret = selected_con - selected_dead - selected_rec
                sel_death_rate = round((selected_dead / selected_con) * 100, 2)
                a = True
        data = requests.get(
            "https://pkgstore.datahub.io/core/country-list/data_json/data/8c458f2d15d9f2119654b29ede6e45b8/data_json.json")

        final = data.text

        smit = json.loads(final)

        code = "IN"
        # print(smit)
        for c in smit:
            if selected_name == c['Name'] or selected_name == c['Name'].lower() or selected_name == c['Name'].upper():
                code = c['Code']
                break

        if not a:
            error = "This Country is not found make sure you type country name properly!!"
        context = {'form': form,
                   'list': list_l,
                   "top_t": top_t,
                   "top_t_con": top_t_con,
                   "top_t_dead": top_t_dead,
                   "top_t_rec": top_t_rec,
                   "top_t_tret": top_t_tret,
                   "all_con": all_con,
                   "all_dead": all_dead,
                   "all_rec": all_rec,
                   "death_rate": death_rate,
                   "selected_name": selected_name,
                   "selected_con": selected_con,
                   "selected_rec": selected_rec,
                   "selected_dead": selected_dead,
                   "selected_tret": selected_tret,
                   "sel_death_rate": sel_death_rate,
                   "error": error,
                   "code": code
                   }
        return render(request, 'data/main.html', context)
    else:
        code = "IN"
        form = Searchform()
        context = {'form': form,
                   'list': list_l,
                   "top_t": top_t,
                   "top_t_con": top_t_con,
                   "top_t_dead": top_t_dead,
                   "top_t_rec": top_t_rec,
                   "top_t_tret": top_t_tret,
                   "all_con": all_con,
                   "all_dead": all_dead,
                   "all_rec": all_rec,
                   "death_rate": death_rate,
                   "selected_name": selected_name,
                   "selected_con": selected_con,
                   "selected_rec": selected_rec,
                   "selected_dead": selected_dead,
                   "selected_tret": selected_tret,
                   "code": code,
                   "sel_death_rate": sel_death_rate,

                   }
        return render(request, 'data/main.html', context)


def sug(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            mob = form.cleaned_data['mob']
            msg = form.cleaned_data['msg']
            a = Review(name=name, mob=mob, msg=msg)
            a.save()
            return redirect('/')

        else:
            form = ReviewForm()
            return render(request, 'data/contact.html', {'form': form})
    else:
        form = ReviewForm()
        return render(request, 'data/contact.html', {'form': form})


def rank(request):
    data_json = requests.get("https://api.covid19api.com/summary")

    data = data_json.text
    data_d = json.loads(data)
    list_l = data_d['Countries']
    list_l.pop(0)
    list_l.pop(0)
    return render(request, 'data/rank.html', {'list_l': list_l})

data/templates/data/contact.html
{% load static %}
<!doctype html>
<html>
<head>
	     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <link href="./main.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>COVIDSTATS
	</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    
	 <style>
.mobile-container {
  max-width: 480px;
  margin: auto;
  background-color: #555;
  height: 500px;
  color: white;
  border-radius: 10px;
}

.topnav {
  overflow: hidden;
  background-color: #333;
  position: relative;
  max-height: 10%;
}

.topnav #myLinks {
  display: none;
}

.topnav a {
  color: white;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  display: block;
}

.topnav a.icon {
  background: black;
  display: block;
  position: absolute;
  right: 0;
  top: 0;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.active {
  background-color: #595252;
  color: white;
}
input[type=text] {
  width: 40%px;
  box-sizing: border-box;
  border: 2px solid #ccc;
  border-radius: 4px;
  font-size: 19px;
  background-color: white;
  background-image: url('https://pngimage.net/searchicon-png-3/');
  background-position: 10px 10px; 
  background-repeat: no-repeat;
  padding: 5px 20px 5px 40px;
  padding-left: 0px
  -webkit-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;
}

input[type=text]:focus {
  width: 95%;
}
form.example button {
  float: left;
  width: 5%;
  padding-top: 10px;
  padding-bottom: 10px;
  background: #2196F3;
  color: white;
  font-size: 19px;
  border: 1px solid grey;
  border-right:none;
border-radius: 4px;
  cursor: pointer;
}

form.example button:hover {
  background: #0b7dda;
}

form.example::after {
  content: "";
  clear: both;
  display: table;
}
.contact-section {
  padding-top: 75px;
  padding-bottom: 80px;
}

.contact-title {
  margin-bottom: 30px;
}

.contact-title h4 {
  color: #252525;
  font-weight: 700;
  margin-bottom: 16px;
}

.contact-widget .cw-item {
  background: #ffffff;
  margin-bottom: 11px;
  -webkit-box-shadow: 0px 8px 35px 10px #E8E8E8;
  box-shadow: 0px 8px 35px 10px #E8E8E8;
  padding-left: 25px;
  padding-top: 15px;
  padding-bottom: 15px;
  border-radius: 10px;
}

.contact-widget .cw-item .ci-icon {
  float: left;
  margin-top: 12px;
}

.contact-widget .cw-item .ci-icon i {
  font-size: 30px;
  color: #b2b2b2;
}

.contact-widget .cw-item .ci-text {
  display: table;
  padding-left: 30px;
}

.contact-widget .cw-item .ci-text span {
  color: #b2b2b2;
  font-size: 16px;
}

.contact-widget .cw-item .ci-text p {
  font-size: 18px;
  color: #252525;
  margin-bottom: 0;
}

.contact-form .leave-comment h4 {
  color: #292f3b;
  font-weight: 700;
  margin-bottom: 20px;
}

.contact-form .leave-comment p {
  margin-bottom: 38px;
}

.contact-form .leave-comment .comment-form input {
  width: 100%;
  font-size: 16px;
  color: #636363;
  height: 50px;
  border: 1px solid #ebebeb;
  border-radius: 5px;
  padding-left: 20px;
  margin-bottom: 30px;
}

.contact-form .leave-comment .comment-form textarea {
  width: 100%;
  resize: none;
  font-size: 16px;
  color: #636363;
  height: 150px;
  border: 1px solid #ebebeb;
  border-radius: 5px;
  padding-left: 20px;
  padding-top: 10px;
  margin-bottom: 35px;
}

.contact-form .leave-comment .comment-form .site-btn {
  padding: 13px 35px 11px;
}

.copyright-text {
  float: left;
  font-size: 16px;
  color: #b2b2b2;
}
.footer-section {
  background: #191919;
  padding-top: 75px;
}
</style>
   
	</head>
	<body>
		<div class="topnav">
  <a href="main.html" ><span style="font-family: 'Lobster', cursive;font-size: large;">COVIDSTATS</span></a>
  <div id="myLinks">
    <a href="/">Dashboard</a>
    <a href="/rank/">World List</a>
    <a href="/sug/" class="active">Suggestions</a>
  </div>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>
 <section class="contact-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <div class="contact-title">
                        <h4>Contacts Us</h4>
                        <p>Hello guys,We are team Smit&Smit.We are novice developers making a small effort.If you have any suggestion or query regarding this website or do want to support us please contact us at following.</p>
                    </div>
                    <div class="contact-widget">
                        <div class="cw-item">
                            <div class="ci-icon">
                                <i class="fa fa-envelope"></i>
                            </div>
                            <div class="ci-text">
                                <span>E-mail:1</span>
                                <p>smitrami7890@gmail.com</p>
                            </div>
                        </div>
                        <div class="cw-item">
                            <div class="ci-icon">
                                <i class="fa fa-envelope"></i>
                            </div>
                            <div class="ci-text">
                                <span>E-mail:2</span>
                                <p>smit3355mistry@gmail.com</p>
                            </div>
                        </div>
                       <!--  <div class="cw-item">
                            <div class="ci-icon">
                                <i class="ti-email"></i>
                            </div>
                            <div class="ci-text">
                                <span>Email:</span>
                                <p>hellocolorlib@gmail.com</p>
                            </div>
                        </div> -->
                    </div>
                </div>
                <div class="col-lg-6 offset-lg-1">
                    <div class="contact-form">
                        <div class="leave-comment">
                            <h4>Leave A Comment</h4>
                            <p>We will reach back later and answer your questions.</p>
                            <form method="post" class="comment-form">
                                {% csrf_token %}
                                                                <div class="row">
                                    <div class="col-lg-6">
                                        <input type="text" name="name" maxlength="50" required="" id="id_name" placeholder="Your name">
                                    </div>
                                    <div class="col-lg-6">
                                        <input type="number" name="mob" min="-9223372036854775808" max="9223372036854775807" required="" id="id_mob" placeholder="Your Number">
                                    </div>
                                    <div class="col-lg-12">
                                        <textarea id="id_msg" name="msg" maxlength="1000" required="" placeholder="Your message"></textarea>
                                        <button type="submit" class="site-btn" style="background-color: #e7ab3c;border-radius: 7px;">Send message</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
     <footer>
       <footer  >
       <div class="col-lg-12">
                        <div class="copyright-text">This website is created by SMIT&SMIT.<br>
                            For more information about COVID-19 visit <a href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019">https://www.who.int/</a>
                        </div>
                      </div>
                    </footer>
<script>
function myFunction() {
  var x = document.getElementById("myLinks");
  if (x.style.display === "block") {
    x.style.display = "none";
  } else {
    x.style.display = "block";
  }
}
</script>
  </body>
</html>

data/templates/data/form.html
{% load static %}
<html>

<head>


    <title>form</title>
</head>
<body>
<img src="{% static 'images/about.jpg' %}">
<h1>Give your message here</h1>
<form method="post">
    {% csrf_token %}
{{ form.as_p }}
<input type="submit" value="submit">

    </form>
</body>

</html>

data/templates/data/index.html
<h1>COVID-19</h1>
<a href="reviews/">Suggestions</a>

<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="search">
</form>
<strong>{{ error }}</strong>
  <h1>{{ selected_name }}
<img src="https://www.countryflags.io/{{ code }}/shiny/64.png"></h1>
<ul>  <li>Total Confirmed: {{ selected_con }}</li>
  <li>Deaths: {{ selected_dead }}</li>
  <li>Recovered: {{ selected_rec }}</li>
  <li>Death Rate: {{ sel_death_rate }}% </li>
</ul>
<div id="piechart"></div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">
// Load google charts
google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawChart);

// Draw the chart and set the chart values
function drawChart() {
  var data = google.visualization.arrayToDataTable([
  ['Phase', 'Person'],
  ['Recovered', {{ selected_rec }}],
  ['Death', {{ selected_dead }}],
  ['treatment on', {{ selected_tret }}]
]);

  // Optional; add a title and set the width and height of the chart
  var options = {'title':'Scenario in {{ selected_name }}', 'width':750, 'height':600};

  // Display the chart inside the <div> element with id="piechart"
  var chart = new google.visualization.PieChart(document.getElementById('piechart'));
  chart.draw(data, options);
}
</script>
<ul>
  <h1>Whole World</h1>
  <li>Total Confirmed: {{ all_con }}</li>
  <li>Deaths: {{ all_dead }}</li>
  <li>Recovered: {{ all_rec }}</li>
  <li>Death Rate: {{ death_rate }}% </li>
</ul>
<h2>Top-10</h2>

<table border="1">
{% for g in top_t %}
<tr><td>{{ g.Country }}</td><td>{{ g.TotalConfirmed }}</td></tr>
{% endfor %}</table>


<div class="piechart"></div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">
// Load google charts
google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawChart);

// Draw the chart and set the chart values
function drawChart() {
  var data = google.visualization.arrayToDataTable([
  ['Phase', 'Person'],
  ['Recovered', {{ top_t_rec }}],
  ['Death', {{ top_t_dead }}],
  ['treatment on', {{ top_t_tret }}]
]);

  // Optional; add a title and set the width and height of the chart
  var options = {'title':'Scenario in top 10', 'width':750, 'height':600};

  // Display the chart inside the <div> element with id="piechart"
  var chart = new google.visualization.PieChart(document.getElementById('piechart'));
  chart.draw(data, options);
}
</script>

<table border="1">



  <tr>

    <th>Country</th><th>Total Confirmed Cases</th><th>Total Deaths</th><th>Recovered</th>
  </tr>

{% for l in list %}
  <tr>
    <td>{{ l.Country }}</td><td>{{ l.TotalConfirmed }}</td><td>{{ l.TotalDeaths }}</td>
    <td>{{ l.TotalRecovered }}</td>

  </tr>

{% endfor %}
</table>

data/templates/data/rank.html
{% load static %}
<!doctype html>
<html>
<head>
	   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <link href="{% static 'main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>COVIDSTATS
	</title>
	 <style>
	 .rami{
    font-family:'Merriweather', serif;
    font-weight:bolder;
    font-size:auto;
}
.mobile-container {
  max-width: 480px;
  margin: auto;
  background-color: #555;
  height: 500px;
  color: white;
  border-radius: 10px;
}

.topnav {
  overflow: hidden;
  background-color: #333;
  position: relative;
  max-height: 10%;
}

.topnav #myLinks {
  display: none;
}

.topnav a {
  color: white;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  display: block;
}

.topnav a.icon {
  background: black;
  display: block;
  position: absolute;
  right: 0;
  top: 0;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.active {
  background-color: #595252;
  color: white;
}
input[type=text] {
  width: 40%px;
  box-sizing: border-box;
  border: 2px solid #ccc;
  border-radius: 4px;
  font-size: 19px;
  background-color: white;
  background-image: url('https://pngimage.net/searchicon-png-3/');
  background-position: 10px 10px; 
  background-repeat: no-repeat;
  padding: 5px 20px 5px 40px;
  padding-left: 0px
  -webkit-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;
}

input[type=text]:focus {
  width: 95%;
}
form.example button {
  float: left;
  width: 5%;
  padding-top: 10px;
  padding-bottom: 10px;
  background: #2196F3;
  color: white;
  font-size: 19px;
  border: 1px solid grey;
  border-right:none;
border-radius: 4px;
  cursor: pointer;
}

form.example button:hover {
  background: #0b7dda;
}

form.example::after {
  content: "";
  clear: both;
  display: table;
}
.copyright-text {
  float: left;
  font-size: 16px;
  color: #b2b2b2;
}
.footer-section {
  background: #191919;
  padding-top: 75px;
}
</style>
   
	</head>
	<body>
		<div class="topnav">
  <a href="/" ><span style="font-family: 'Lobster', cursive;font-size: large;">COVIDSTATS</span></a>
  <div id="myLinks">
    <a href="/">Dashboard</a>
    <a href="/rank/" class="active">World List</a>
    <a href="/sug/">Suggestions</a>
  </div>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>
 <br/>
 <br/>
  <div class="row">
          <div class="col-md-12">
            <h2 style="text-align: center;color:#1c0d0d; " class="rami">Global Risk List</h2>
          </div>
          <br/>
  </div>
  <table class="table table-dark table-striped">
    <thead>
      <tr>

        <th>Name</th>
        <th>Confirmed</th>
        <th>Deaths</th>
        <th>Recovered</th>
      </tr>
    </thead>
    <tbody>
    
         {% for g in list_l %}
            <tr>
                <td>{{ g.Country }}</td>
                <td>{{ g.TotalConfirmed }}</td>
                <td>{{ g.TotalDeaths }}</td>
                <td>{{ g.TotalRecovered }}</td>
            </tr>
        {% endfor %}
    </tbody>
  </table>
  <footer>
       <footer  >
       <div class="col-lg-12">
                        <div class="copyright-text">This website is created by SMIT&SMIT.<br>
                            For more information about COVID-19 visit <a href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019">https://www.who.int/</a>
                        </div>
                      </div>
                    </footer>
<script>
function myFunction() {
  var x = document.getElementById("myLinks");
  if (x.style.display === "block") {
    x.style.display = "none";
  } else {
    x.style.display = "block";
  }
}
</script>
	</body>
</html>